#!/bin/sh
#
# This stub needs to have an actual consumer hooked up to it if you would like to run search

export HOME=/home/szimpatikus
cd $HOME/reddit/r2
exec 2>&1
exec setuidgid szimpatikus /usr/local/bin/paster run run.ini -c "from r2.lib import amqp; amqp.consume_items('searchchanges_q', lambda x: 0)"
